### ISSUE TITLE
visualization.py 

### ISSUE THREAD

**Issue by hhhhsmx** [leofansq/SCF-Net#10]
Regarding the command of visualization“python visualization.py --dataset 'XXX' --ply_path "path_to_origin_ply" --label_path "path_to_label"”, Only need to modify the “dataset‘XXX’”？

**Comment by leofansq** [comment]
all three (--dataset --ply_path --label_path) need to be modified

**Comment by hhhhsmx** [comment]
> path_to_origin_ply

’path_to_origin_ply‘，Is this the path filled in with ‘origin_ply’?

**Comment by leofansq** [comment]
> 

yep

**Comment by leofansq** [comment]
> > path_to_origin_ply
> 
> ’path_to_origin_ply‘，Is this the path filled in with ‘origin_ply’?

yep

**Comment by hhhhsmx** [comment]
> > > path_to_origin_ply
> > 
> > 
> > ’path_to_origin_ply‘，Is this the path filled in with ‘origin_ply’?
> 
> yep

ok,thank you very much!

**Comment by hhhhsmx** [comment]
Hello, can you tell us what to fill in this 'path_to_origin_ply' and 'path_to_label'?I always make mistakes
![image](https://user-images.githubusercontent.com/93530021/194072004-ac4a27d7-591b-44aa-a701-c15f738d1a7d.png)

**Comment by leofansq** [comment]
> Hello, can you tell us what to fill in this 'path_to_origin_ply' and 'path_to_label'?I always make mistakes ![image](https://user-images.githubusercontent.com/93530021/194072004-ac4a27d7-591b-44aa-a701-c15f738d1a7d.png)

--ply_path "./data/S3DIS/origin_ply/example.ply"

**Comment by hhhhsmx** [comment]
> 

I ran successfully and thank you very much for your guidance!
