### ISSUE TITLE
After training and testing, the ply file generated by the test cannot be opened

### ISSUE THREAD

**Issue by 962858249** [leofansq/SCF-Net#3]
Excuse me, is the ply file in the generated test/s3dis_preds containing point cloud x, y, z coordinates? Why can't the resulting ply file open? And is your point cloud forecast results can send me a copy? My mailbox is 201911160102@mail.bun.edu.cn, thank you!

**Comment by leofansq** [comment]
The generated ply files contain the predictions and the labels. You can read these files using the function read_ply in helper_ply.py. Besides, we have provided the visualization.py for visualization, and it can also help you understand how to use the ply files.

**Comment by 962858249** [comment]
Thank you very much for your reply. I didn't notice you when browsing the document. Now I have seen the visualization results of point cloud. Thank you again for your reply!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leofansq/SCF-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 晚上10:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leofansq/SCF-Net] After training and testing, the ply file generated by the test cannot be opened (#3)





 
The generated ply files contain the predictions and the labels. You can read these files using the function read_ply in helper_ply.py. Besides, we have provided the visualization.py for visualization, and it can also help you understand how to use the ply files.
